version: '3.9'
services:
  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "docker_db"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "user1"
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:6.0
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    hostname: "devops-go"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./data/rabbitmq_mnesia:/var/lib/rabbitmq/mnesia

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
    depends_on:
      - mysql
      - redis
      - rabbitmq
    entrypoint: [ "/app/wait-for.sh", "mysql:3306", "redis:6379", "rabbitmq:5672", "--", "/app/main"]