version: '3.9'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "docker_db"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "user1"
    ports:
      - "3307:3306"
    volumes:
      - ~/devops/go-db/data/mysql:/var/lib/mysql

  redis:
    image: redis:6.0
    ports:
      - "6380:6379"
    volumes:
      - ~/devops/go-db/data/redis:/var/lib/redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ~/devops/go-db/data/rabbitmq:/var/lib/rabbitmq

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
    depends_on:
      - mysql
      - redis
      - rabbitmq
    entrypoint: [ "/app/wait-for.sh", "mysql:3306", "redis:6379", "rabbitmq:5672", "--", "/app/main"]